// 錯誤碼 enum + APIError（SPEC-C §6）

// 認證相關（7 個）
// 裝置相關（4 個）
// 集體智慧（5 個）
// L0 相關（6 個）
// 互助相關（7 個）
// 備份相關（4 個）
// Sub-Key 相關（2 個）
// 版本相關（2 個）
// WebSocket 相關（5 個）
// 通用（3 個）
// 總計：45 個

export enum ErrorCode {
  // 認證
  AUTH_MISSING_HEADERS = 'AUTH_MISSING_HEADERS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_DEVICE_NOT_FOUND = 'AUTH_DEVICE_NOT_FOUND',
  AUTH_GOOGLE_REQUIRED = 'AUTH_GOOGLE_REQUIRED',
  AUTH_GOOGLE_TOKEN_INVALID = 'AUTH_GOOGLE_TOKEN_INVALID',
  AUTH_GOOGLE_ALREADY_BOUND = 'AUTH_GOOGLE_ALREADY_BOUND',

  // 裝置
  DEVICE_ALREADY_REGISTERED = 'DEVICE_ALREADY_REGISTERED',
  DEVICE_FINGERPRINT_MISMATCH = 'DEVICE_FINGERPRINT_MISMATCH',
  DEVICE_SUSPENDED = 'DEVICE_SUSPENDED',
  DEVICE_TOKEN_MISMATCH = 'DEVICE_TOKEN_MISMATCH',

  // 集體智慧
  TELEMETRY_RATE_LIMITED = 'TELEMETRY_RATE_LIMITED',
  TELEMETRY_BATCH_TOO_LARGE = 'TELEMETRY_BATCH_TOO_LARGE',
  TELEMETRY_INVALID_SCHEMA = 'TELEMETRY_INVALID_SCHEMA',
  TELEMETRY_DUPLICATE_BATCH = 'TELEMETRY_DUPLICATE_BATCH',
  FEEDBACK_RATE_LIMITED = 'FEEDBACK_RATE_LIMITED',

  // L0
  L0_DAILY_LIMIT_REACHED = 'L0_DAILY_LIMIT_REACHED',
  L0_KEY_NOT_FOUND = 'L0_KEY_NOT_FOUND',
  L0_SERVICE_UNAVAILABLE = 'L0_SERVICE_UNAVAILABLE',
  L0_DONATE_INVALID_KEY = 'L0_DONATE_INVALID_KEY',
  L0_DONATE_DUPLICATE = 'L0_DONATE_DUPLICATE',
  L0_DONATE_RATE_LIMITED = 'L0_DONATE_RATE_LIMITED',

  // 互助
  AID_NOT_ENABLED = 'AID_NOT_ENABLED',
  AID_NO_HELPER = 'AID_NO_HELPER',
  AID_RATE_LIMITED = 'AID_RATE_LIMITED',
  AID_DAILY_LIMIT_REACHED = 'AID_DAILY_LIMIT_REACHED',
  AID_REQUEST_TIMEOUT = 'AID_REQUEST_TIMEOUT',
  AID_PAYLOAD_TOO_LARGE = 'AID_PAYLOAD_TOO_LARGE',
  AID_COOLDOWN = 'AID_COOLDOWN',

  // 備份
  BACKUP_TOO_LARGE = 'BACKUP_TOO_LARGE',
  BACKUP_NOT_FOUND = 'BACKUP_NOT_FOUND',
  BACKUP_CHECKSUM_MISMATCH = 'BACKUP_CHECKSUM_MISMATCH',
  BACKUP_QUOTA_EXCEEDED = 'BACKUP_QUOTA_EXCEEDED',

  // Sub-Key
  SUBKEY_INVALID = 'SUBKEY_INVALID',
  SUBKEY_ISSUER_OFFLINE = 'SUBKEY_ISSUER_OFFLINE',

  // 版本
  VERSION_TOO_OLD = 'VERSION_TOO_OLD',
  VERSION_CHECK_FAILED = 'VERSION_CHECK_FAILED',

  // WebSocket
  WS_AUTH_FAILED = 'WS_AUTH_FAILED',
  WS_SUBSCRIBE_INVALID = 'WS_SUBSCRIBE_INVALID',
  WS_CHAT_RATE_LIMITED = 'WS_CHAT_RATE_LIMITED',
  WS_CHAT_MESSAGE_TOO_LONG = 'WS_CHAT_MESSAGE_TOO_LONG',
  WS_INVALID_MESSAGE_FORMAT = 'WS_INVALID_MESSAGE_FORMAT',

  // 通用
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INVALID_REQUEST = 'INVALID_REQUEST',
}

export interface APIError {
  error: ErrorCode;
  message: string;
  suggestion?: string;
  retry_after?: number;
  details?: unknown;
}

// HTTP 狀態碼對應表
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.AUTH_MISSING_HEADERS]: 401,
  [ErrorCode.AUTH_INVALID_TOKEN]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_DEVICE_NOT_FOUND]: 401,
  [ErrorCode.AUTH_GOOGLE_REQUIRED]: 401,
  [ErrorCode.AUTH_GOOGLE_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_GOOGLE_ALREADY_BOUND]: 409,
  [ErrorCode.DEVICE_ALREADY_REGISTERED]: 409,
  [ErrorCode.DEVICE_FINGERPRINT_MISMATCH]: 403,
  [ErrorCode.DEVICE_SUSPENDED]: 403,
  [ErrorCode.DEVICE_TOKEN_MISMATCH]: 403,
  [ErrorCode.TELEMETRY_RATE_LIMITED]: 429,
  [ErrorCode.TELEMETRY_BATCH_TOO_LARGE]: 413,
  [ErrorCode.TELEMETRY_INVALID_SCHEMA]: 400,
  [ErrorCode.TELEMETRY_DUPLICATE_BATCH]: 409,
  [ErrorCode.FEEDBACK_RATE_LIMITED]: 429,
  [ErrorCode.L0_DAILY_LIMIT_REACHED]: 429,
  [ErrorCode.L0_KEY_NOT_FOUND]: 404,
  [ErrorCode.L0_SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.L0_DONATE_INVALID_KEY]: 400,
  [ErrorCode.L0_DONATE_DUPLICATE]: 409,
  [ErrorCode.L0_DONATE_RATE_LIMITED]: 429,
  [ErrorCode.AID_NOT_ENABLED]: 400,
  [ErrorCode.AID_NO_HELPER]: 503,
  [ErrorCode.AID_RATE_LIMITED]: 429,
  [ErrorCode.AID_DAILY_LIMIT_REACHED]: 429,
  [ErrorCode.AID_REQUEST_TIMEOUT]: 503,
  [ErrorCode.AID_PAYLOAD_TOO_LARGE]: 413,
  [ErrorCode.AID_COOLDOWN]: 429,
  [ErrorCode.BACKUP_TOO_LARGE]: 413,
  [ErrorCode.BACKUP_NOT_FOUND]: 404,
  [ErrorCode.BACKUP_CHECKSUM_MISMATCH]: 400,
  [ErrorCode.BACKUP_QUOTA_EXCEEDED]: 429,
  [ErrorCode.SUBKEY_INVALID]: 403,
  [ErrorCode.SUBKEY_ISSUER_OFFLINE]: 503,
  [ErrorCode.VERSION_TOO_OLD]: 400,
  [ErrorCode.VERSION_CHECK_FAILED]: 500,
  [ErrorCode.WS_AUTH_FAILED]: 401,
  [ErrorCode.WS_SUBSCRIBE_INVALID]: 400,
  [ErrorCode.WS_CHAT_RATE_LIMITED]: 429,
  [ErrorCode.WS_CHAT_MESSAGE_TOO_LONG]: 400,
  [ErrorCode.WS_INVALID_MESSAGE_FORMAT]: 400,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.INVALID_REQUEST]: 400,
};
